version: '3'
services:
  app:
    build: .
    ports:
      - "8080:3000"
    volumes: 
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - /app/.git
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    logging:     
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bundle:
    driver: local
